README.md, src/HeatPump.cpp, src/HeatPump.h
Added some rough code to request updates from the heatpump, and also fix a bug with the vane SWING setting.
=> Get updates from heatpump

src/HeatPump.cpp
=> Revert "Update HeatPump.cpp"

examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino, src/HeatPump.cpp, src/HeatPump.h
Fixes wideVane, fixes temp found in alternate byte with 0.5 resolution and should correct any first boot issues.
=> Control packets

examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
=> fix custom packet

examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino, src/HeatPump.cpp, src/HeatPump.h
Can detect from modes cool,dry and heat...but not yet set
=> iSee Synchronization

src/HeatPump.cpp
- checksum now calculated for packets that are smaller than a full 22 byte packet
- also added a check to make sure packet size doesn't exceed 22 bytes (PACKET_LEN)
=> added checksum for small custom packets

examples/OTA-mitsubishi_heatpump_mqtt_esp8266/OTA-mitsubishi_heatpump_mqtt_esp8266.h, examples/OTA-mitsubishi_heatpump_mqtt_esp8266/OTA-mitsubishi_heatpump_mqtt_esp8266.ino
@SwiCago I have tested this with my IDE and it works.
=> OTA example

examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino, src/HeatPump.cpp, src/HeatPump.h
Detect loss of connection and auto reconnect in sync, also added a bool
for connect, so that sketch can wait till connected before continuing
=> Auto Reconnect

examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino, src/HeatPump.h
as per https://github.com/SwiCago/HeatPump/issues/20
=> changed millis() variables to unsigned long

src/HeatPump.cpp, src/HeatPump.h
As per discussions in #57, this saves approximately 700B.
=> Change to use char*

src/HeatPump.cpp, src/HeatPump.h
Reverts SwiCago/HeatPump#58
@schotime this pull request does not work with any of the examples.
Please test your new version with the examples. Get them to compile correctly and request a new pull. 
Thanks
=> Revert "Change to use char*"

src/HeatPump.cpp
Fixes bracket that went missing, L128
=> Added missing bracket

integrations/OpenHAB/transform/HPMode.map
=> added FAN and AUTO mode

src/HeatPump.h
INFOHEADER_LEN placed in the correct place
=> INFOHEADER_LEN place

integrations/OpenHAB/mitsubishi_heatpump_mqtt_esp8266_template/mitsubishi_heatpump_mqtt_esp8266.h, integrations/OpenHAB/mitsubishi_heatpump_mqtt_esp8266_template/mitsubishi_heatpump_mqtt_esp8266_template.ino
Introduced isCelsius bool in .h file to have temperature in Celsius or Fahrenheit
=> Celsius fahrenheit switch

integrations/home-assistant.io/mitsubishi_mqtt.py
HA Climate platform now required standardized operation mode, as STATE_* like STATE_COOL or STATE_FAN_ONLY instead of COOL or FAN. Otherwise it will still work on HA interface but not work with other platform like Apple Homekit / Google Assistant. Instead of modify HeatPump.h, operation_mode value are mapped and converted on the fly. Also capitalized FAN and SWING mode to match OPERATION MODE interface.
=> Add support for Apple Homekit / Google Assistant

README.md
=> Add link to pre-crimped jumper cables

integrations/home-assistant.io/custom_components/mitsubishi_mqtt/climate.py
Update for homeassistant >= 0.92 integration
=> Breaking changes for homeassistant >= 0.92

integrations/home-assistant.io/custom_components/mitsubishi_mqtt/climate.py
Home Assistant 0.90 introduced a breaking change for MQTT climate components [1], changing the method signature of message_received to take a single Message object.
[1] https://github.com/home-assistant/home-assistant/pull/21959
=> Change method signature of message_received to work with HA 0.90 and later

README.md
Added a wayback machine link as the site no longer exists
=> Added a wayback machine link as the site no longer exists

README.md
=> Update gitter.im link

src/HeatPump.cpp
Fix issue #207 with ESP32 default UART pin
=> Fix issue #207
