SwiCago/HeatPump

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- src/HeatPump.cpp
- src/HeatPump.h
Hi @SwiCago 
Thanks for merging #2! With that out of the way, I would like to slowly work through some of the other ideas for improvements (including some code doco) that I have.
This pull request is for some callback functions, to allow users of the library to code some action in their sketches whenever certain events happen in the library. The two events for callbacks I have in mind are:
- whenever the heatpump's settings are changed (for example if someone presses a button on the remote control, the sketch will be able to easily execute some code
- whenever a valid (checksum passes) packet is received from the heatpump (this one is mostly for debugging - it creates an wasy way for the user's sketch to get every packet that is received from the heatpump, without putting any debug code …
> callback functions - settingsChangedCallback and packetReceivedCallback

- src/HeatPump.cpp
@SwiCago - thought I would wrap up just this change in one commit and pull request, as I figure it's better to have more small commits/merges than fewer larger ones!
RE: a public loop() function, I have been thinking about this and decided there is probably no need. I did some research and couldn't find anything that pointed to a standard practice of calling a library function "loop" if it should be called every iteration of the sketch's loop, so I think sync() is just fine. Plus it makes sense - it's keep the ESP8266 or whatever is running the library in "sync" with the heatpump. So I think it's good as is. Unless you see another reason?
I use [http://home-assistant.io](http://home-assistant.io) for controlling the heatpump and automation. I will upload my heatpump configuration file in …
> removed superfluous class name and Paamayim Nekudotayim from function calls

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- src/HeatPump.cpp
- src/HeatPump.h
This pull request resolves the issues identified in #9 and #10.
Note that public method setPacketReceivedCallback() has changed to setPacketCallback() and has an extra parameter. Function declaration is now:
```
void HeatPump::setPacketCallback(void (*packetCallback)(byte* data, unsigned int length, char* packetDirection));
```
I have tested the code and my heatpump, and @uronito has confirmed the new code works too. See https://github.com/SwiCago/HeatPump/issues/11#issuecomment-280637344 for more info.
> sync settings during update() call, and set wantedSettings to currentSettings once known on first sync

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.h
- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- made use of the roomTempChangedCallback callback to send current room temp as it changes. 60s periodical send is still there too
- also added retain flag to room temperature message
- these changes should close https://github.com/SwiCago/HeatPump/issues/8
- added SEND_ROOM_TEMP_INTERVAL_MS constant (set to 60000ms - 60s) for setting temperature update interval
- added wifi/mqtt/etc settings to a header file, to make maintaining the example easier when pushing to github!
- few other general formatting and removed unused lastSettings variable
Tested on my heatpump, no problems. This will close #8 too.
> mqtt example: roomTempChangedCallback and settings header file

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- keywords.txt
- src/HeatPump.cpp
- src/HeatPump.h
**added keywords.txt file**
- because who doesn't like highlighted keywords!
**changed connect() to use writePacket() and general clean up  …**
- connect() uses writePacket() now so that all packet writing is done through this method, meaning that the packetCallback will be fired when connecting to the heatpump (previously it wasn't)
- removed lots of magic numbers
- ensured all variables are in camelCase and not underscore_separated
- general formatting - consistent curly brace position on if() and for()
**reordered code to capture connect() packets for debug  …**
- previously connect was called before the packetCallback was set, and before mqtt connection was established
> add keywords.txt, connect() uses writePacket(), general code clean

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- src/HeatPump.cpp
- src/HeatPump.h
- the wide vane setting is sent on byte 18 (assuming first byte is 0)
- the bitmap control byte value for this packet is set in byte 7 (not 6 as for the other settings) and has a value of 0x01
This resolves #7 and is being discussed in #25 as well.
I also did some work on the custom packet sender to make it work. Currently (for example) I send a payload over mqtt of:
```
{"custom": "41 01 30 10 01 08 01 00 00 07 02 00 00 00 00 00 00 08 00 00 "}
```
note that the space at the end is important, or else the last byte isn't sent
> wide vane (horizontal vane) is now working!

- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- src/HeatPump.cpp
- any number of bytes from 0-20 can be sent now
- checksum only added to end of packet if it's a full packet
- stopped the mqtt example from sending roomTemperature on first loop(), as it was always 0. It now sends it after 60s (and then every 60s), and within that first 60s it will be received by heatpump and the callback will fire and send the initial reading
- also removed the need to add a space at the end of the byte string that is published to mqtt - it's now much more forgiving, and (for example to send CONENCT) `{"custom": "5a 01 30 02 ca 01 a8"}` will work
> improved custom packet sender

- integrations/home-assistant.io/README.md
The Temperature topic in the readme was invalidated last year according to the commit history.  The HASSIO Plugin appears to parse the data from the Status JSON now.
Took me a bit to figure out why things were not working...  Figured I would save others the time.
> Update Temp State topic

- examples/HP_cntrl_Fancy_web/HP_cntrl_Fancy_web.ino
- examples/HP_cntrl_esp8266/HP_cntrl_esp8266.ino
- examples/mitsubishi_heatpump_mqtt_esp8266/mitsubishi_heatpump_mqtt_esp8266.ino
- integrations/OpenHAB/mitsubishi_heatpump_mqtt_esp8266_template/mitsubishi_heatpump_mqtt_esp8266_template.ino
- src/HeatPump.cpp
- src/HeatPump.h
As discussed in #96 and previously attempted in #60, I've converted all the use of `String` to store the various settings values to `const char*`. This should reduce memory usage at little cost to library users, who can continue to wrap the `char*` with `String` instances if they like.
I've also updated - but *not tested on hardware* - the examples.
> Use const char* instead of strings

- integrations/home-assistant.io/mitsubishi_mqtt.py
Fix the configuration validation error issue due to Home Assistant disallow arbitrary configuration attributes in MQTT platforms.  See the issue log of HA for details: https://github.com/home-assistant/home-assistant/pull/20578
> Fix integration with Home Assistant v0.87

- integrations/home-assistant.io/mitsubishi_mqtt.py
While the integration stores/accesses the hass instance at `_hass`, its
parent expects `hass`.
> Add `self.hass` attribute to please parent-class accessor

- src/HeatPump.cpp
fix these 3 compiler warnings:
HeatPump.cpp: In member function 'bool HeatPump::connect(HardwareSerial*)':
HeatPump.cpp:87:1: warning: no return statement in function returning non-void [-Wreturn-type]
}
^
HeatPump.cpp: In member function 'void HeatPump::createInfoPacket(byte*, byte)':
HeatPump.cpp:466:68: warning: operation on '((HeatPump*)this)->HeatPump::infoMode' may be undefined [-Wsequence-point]
infoMode = (infoMode == (INFOMODE_LEN - 1)) ? 0 : infoMode += 1;
^
HeatPump.cpp: In member function 'int HeatPump::readPacket()':
HeatPump.cpp:595:21: warning: unused variable 'receivedRoomTemp' [-Wunused-variable]
float receivedRoomTemp;
> fix compiler warnings

- integrations/home-assistant.io/custom_components/mitsubishi_mqtt/manifest.json
HA need a manifest file or it will not load the component properly
> This is needed cause of new home assistant rules

- src/HeatPump.cpp
- src/HeatPump.h
sync() will now return immediately after sending instead of waiting a full second before reading. 
This speeds up the loop() and allows me to respond to http requests much quicker.
A flag is set to schedule the reading after the chosen delay time has passed. The new canRead() function controls the reading like canSend() does control the sending.
Additionally (and not related to the timing issue) I have added a isConnected() method to expose the connected attribute to library users.
> Make applications more responsive by removing the delay in sync()

- src/HeatPump.cpp
I had the issue described in #69 where setting remote temperature made the heat pump report 10 degrees with an older MSZ-FH35 from 2009. After poking around with custom packets I found that byte 7 affects the temperature with this model. Given the reaction to different values I found the formula used in this patch to work. I've no idea whether this is in fact correct, but at least the reported room temperature follows the set ones. It seems to support 0.5 degree resolution even though the requested temperature can only be set in 1 degree increments.
This patch assumes the devices that use byte 8 don't mind byte 7 being set. If that's not the case, this obviously won't work for everyone.
> Make setRemoteTemperature work with the European MSZ-FH series.

- src/HeatPump.cpp
- src/HeatPump.h
A number of pointers in the HeatPump class were used before they were
initialized, particularly the callback function pointers. This becomes
an issue when an object is created from the class using heap memory, as
there is no guarantee that the memory will be initialized to all zeros
in that case.
> Initialize callback pointers, plus status and settings structs

- src/HeatPump.cpp
- src/HeatPump.h
I found that this was required to get the MSZ-GB50VA working, as described in the commit message. 
I also fixed the callback signature definitions for ESP32.
> Allow explicitly setting baud rate

- README.md
- src/HeatPump.cpp
- src/HeatPump.h
I added some information on how auto update and external update work and their intended use cases.
I also changed `enableExternalUpdate()` to also enable auto update because it had no effect by itself and it’s confusing people.
I believe a better fix would be to make external update work by itself by changing `(autoUpdate && externalUpdate)` to `(autoUpdate || externalUpdate)` but I’m not sure if it’s an acceptable change.
> Updated readme to explain auto update and external update

- src/HeatPump.cpp
**Background:** All `HeatPump::setXXXXXX` functions utilize `HeatPump::lookupByteMapIndex` to look up the index of the provided setting, and ultimately use this index to update `wantedSettings`, which is used to construct packets to send to the Mitsubishi unit. User-provided values are compared with `strcmp` to a list of predefined values in `src/HeatPump.h` to find the index, and ultimately the exact value, of the setting that should be sent to the Mitsubishi unit.
&nbsp;
**Issue:** Users using [mitsubishi2MQTT](https://github.com/gysmo38/mitsubishi2MQTT) to communicate with [Home Assistant](https://www.home-assistant.io/)'s [climate.mqtt](https://www.home-assistant.io/integrations/climate.mqtt) integration are currently unable to control their Mitsubishi units as only lowercase values …
> Perform case-insensitive lookups

- src/HeatPump.h
Fix `warning: missing initializer for member 'heatpumpStatus::compressorFrequency' [-Wmissing-field-initializers]`
> Fix warning in currentStatus initializer.

- src/HeatPump.cpp
- src/HeatPump.h
This is based on monitoring communication between MHK1 and an air handler (PVA) and some Mitsubishi technical documents.
References:
- https://www.mitsubishitechinfo.ca/sites/default/files/Installation_Manual_69-2426-01_0.pdf, page 6
- https://www.mitsubishitechinfo.ca/sites/default/files/IM_PVA_A12_42AA7_PA79D213H09.pdf, page 22
- https://www.mitsubishitechinfo.ca/sites/default/files/SH_PVA-A12_42AA7_201812.pdf, page 21
In order to read the current value of function codes MHK1 sends the following packets:
FC 42 01 30 10 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 5D
FC 42 01 30 10 22 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 5B
The following is returned by the unit:
FC 62 01 30 10 20 06 09 0D 11 16 18 3D 41 45 48 4C 50 54 58 00 8F
FC 62 01 30 10 22 1F 22 24 29 2E 31 36 38 5D 61 65 …
> Added support for getting and setting generic function codes

- src/HeatPump.cpp
- src/HeatPump.h
Currently we strictly read one packet each time `sync()` is called.
This means that if `writePacket()` is ever called twice in a row
before reading, a packet will be permanently buffered.
In cases where you expect to write a packet and receive a response
in the next packet, such as during `update()`, having buffered packets
guarantees you won't receive the correct packet next.
Changing `sync()` and `update()` to flush the serial buffer makes the
behavior much more robust and in my testing has always given me the
0x41 0x61 pair successfully when I call `update()`.
Closes #181
> Read all packets in buffer during sync and before update

- README.md
The existing link no longer works, this alternate one has even more convenient connectors on the other end.
> Readme: Update AliExpress link.

- src/HeatPump.cpp
- src/HeatPump.h
As discussed in https://github.com/SwiCago/HeatPump/issues/192 there is a problem affecting users with external updates enabled - if an update() from heatpump library fails, external update will clobber that change, and therefore the library initiated change will never be applied (a dropped request)
The core logic here - any of these methods will prioritize the library and **trump external updates for 30 seconds**.
- `setPowerSetting`
- `setModeSetting`
- `setTemperature`
- `setFanSpeed`
- `setVaneSetting`
- `setWideVaneSetting`
This will ensure library initiated changes have enough time to be applied, before considering external updates done by someone manually controlling the thermostat, or any other mitsubishi controller.
In short, this gives a more consistent experience for those who …
> Ignore external updates grace period

- CMakeLists.txt
- src/HeatPump.cpp
- src/HeatPump.h
When code in https://github.com/SwiCago/HeatPump/blob/cea90c5ed48d24a904835f8918bd88cbc84cb1be/src/HeatPump.cpp#L175 call, connected state first reset to false even it is true before and blackout about 2 seconds after it online again, my logic check this state to send command to heat pump. So not reset it in the first time after the connection failed or timeout make it more stable.
Also when connect(NULL) call,  the rx, tx set for ESP32 become -1 and it fall back to default hardware pin, two variable store these pin in the first call fix the issue.
> Fix missing UART pin when retry for ESP32. Not reset connected state when retry, make control more stable.

- README.md
- src/HeatPump.cpp
- src/HeatPump.h
With this change and enable fast sync, time sync speed up by 2x.
Expose wantedSettings and lastWanted make mqtt control over Home Assistant more stable, see: https://github.com/dzungpv/mitsubishi2MQTT
> Fix slow sync when using IR or wall remote
